"""Tests builder."""

from pathlib import Path

import pytest

from gendoc.analyzer import analyze_package
from gendoc.builder import SiteBuilder
from gendoc.config import GendocConfig


def test_builder_creates_docs(temp_package, tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)  # hermétique : le builder ne doit rien lire/écrire ailleurs
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"
    cfg.formats = ["mmd", "puml", "svg"]
    cfg.site_name = "Test Docs"

    builder = SiteBuilder(cfg, pkg)
    docs_path = builder.build()

    assert docs_path.exists()
    assert (docs_path / "index.md").exists()
    assert (docs_path / "packages.md").exists()
    assert (docs_path / "diagrams" / "package.mmd").exists()
    assert (docs_path / "diagrams" / "package.puml").exists()
    assert (docs_path / "diagrams" / "package.svg").exists()

    # Modules
    assert (docs_path / "modules").exists()
    modules_files = list((docs_path / "modules").glob("*.md"))
    assert len(modules_files) >= 1

    # API
    assert (docs_path / "api").exists()
    api_files = list((docs_path / "api").glob("*.md"))
    assert len(api_files) >= 1

    # mkdocs.yml
    mkdocs_yml = docs_path.parent / "mkdocs.yml"
    assert mkdocs_yml.exists()
    content = mkdocs_yml.read_text()
    assert "site_name" in content
    assert "mkdocstrings" in content


def test_builder_focus(temp_package, tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"
    cfg.formats = ["mmd", "svg"]
    cfg.focus_class = "User"
    cfg.focus_depth = 1

    builder = SiteBuilder(cfg, pkg)
    docs_path = builder.build()

    assert (docs_path / "focus.md").exists()
    assert (docs_path / "diagrams" / "focus_User.mmd").exists()
    assert (docs_path / "diagrams" / "focus_User.svg").exists()

    focus_content = (docs_path / "focus.md").read_text()
    assert "User" in focus_content


def test_module_pages_image_links_resolve(temp_package, tmp_path: Path):
    """Les liens d'images des pages modules doivent pointer vers des fichiers existants."""
    import re

    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"
    cfg.formats = ["mmd", "puml", "svg"]

    docs_path = SiteBuilder(cfg, pkg).build()

    pages = list((docs_path / "modules").glob("*.md"))
    assert pages
    for page in pages:
        for match in re.finditer(r"!\[[^\]]*\]\(([^)]+)\)", page.read_text()):
            target = (page.parent / match.group(1)).resolve()
            assert target.exists(), f"{page.name}: image cassée -> {match.group(1)}"


def test_build_does_not_touch_cwd_mkdocs(temp_package, tmp_path: Path, monkeypatch):
    """Le builder ne doit jamais écraser le mkdocs.yml du répertoire courant."""
    workdir = tmp_path / "cwd"
    workdir.mkdir()
    user_mkdocs = workdir / "mkdocs.yml"
    user_mkdocs.write_text("site_name: FichierUtilisateur\n")
    monkeypatch.chdir(workdir)

    pkg = analyze_package(temp_package, package_name="testpkg")
    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"
    SiteBuilder(cfg, pkg).build()

    assert user_mkdocs.read_text() == "site_name: FichierUtilisateur\n"


def test_build_preserves_handwritten_mkdocs(temp_package, tmp_path: Path, monkeypatch):
    """Un mkdocs.yml existant sans marqueur gendoc ne doit pas être écrasé."""
    monkeypatch.chdir(tmp_path)
    project = tmp_path / "proj"
    project.mkdir()
    handwritten = project / "mkdocs.yml"
    handwritten.write_text("site_name: FaitMain\n")

    pkg = analyze_package(temp_package, package_name="testpkg")
    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = project / "site"
    cfg.docs_dir = project / "docs"
    with pytest.warns(RuntimeWarning):
        SiteBuilder(cfg, pkg).build()

    assert handwritten.read_text() == "site_name: FaitMain\n"


def test_generated_mkdocs_has_marker_and_is_regenerated(temp_package, tmp_path: Path, monkeypatch):
    """Le mkdocs.yml généré porte un marqueur et peut être régénéré."""
    monkeypatch.chdir(tmp_path)
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"
    SiteBuilder(cfg, pkg).build()

    mk = tmp_path / "mkdocs.yml"
    assert mk.exists()
    assert mk.read_text().lstrip().startswith("# Generated by gendoc")

    cfg.site_name = "NouveauNom"
    SiteBuilder(cfg, pkg).build()
    assert "NouveauNom" in mk.read_text()


def test_pages_show_rendered_diagrams_not_raw_plantuml(temp_package, tmp_path: Path, monkeypatch):
    """Les pages montrent le diagramme Mermaid rendu, pas de bloc PlantUML brut (code)."""
    monkeypatch.chdir(tmp_path)
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.docs_dir = tmp_path / "docs"
    cfg.output_dir = tmp_path / "site"
    docs = SiteBuilder(cfg, pkg).build()

    module_page = (docs / "modules" / "testpkg_models.md").read_text()
    assert "```mermaid" in module_page  # diagramme UML rendu conservé
    assert "@startuml" not in module_page  # plus de PlantUML brut affiché comme code
    assert "```plantuml" not in module_page

    packages_page = (docs / "packages.md").read_text()
    assert "```mermaid" in packages_page
    assert "@startuml" not in packages_page

    # les .puml restent générés et listés (téléchargeables) sur la page diagrammes
    assert (docs / "diagrams" / "testpkg_models.puml").exists()
    assert "testpkg_models.puml" in (docs / "diagrams.md").read_text()


def test_api_pages_hide_raw_source(temp_package, tmp_path: Path, monkeypatch):
    """La doc API ne montre pas le source Python brut (show_source désactivé)."""
    monkeypatch.chdir(tmp_path)
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.docs_dir = tmp_path / "docs"
    cfg.output_dir = tmp_path / "site"
    docs = SiteBuilder(cfg, pkg).build()

    api_page = (docs / "api" / "testpkg_models.md").read_text()
    assert "show_source: false" in api_page
    mkdocs = (docs.parent / "mkdocs.yml").read_text()
    assert "show_source: true" not in mkdocs


def test_module_pages_use_relative_paths(temp_package, tmp_path: Path):
    """Les pages ne doivent pas embarquer de chemins absolus de la machine."""
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"

    docs_path = SiteBuilder(cfg, pkg).build()

    page = (docs_path / "modules" / "testpkg_models.md").read_text()
    assert str(temp_package) not in page
    assert "models.py" in page


def test_mkdocs_nav_has_no_raw_diagram_files(temp_package, tmp_path: Path):
    """La nav MkDocs ne référence pas de fichiers non-markdown (.mmd/.puml)."""
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"

    docs_path = SiteBuilder(cfg, pkg).build()

    mkdocs = (docs_path.parent / "mkdocs.yml").read_text()
    assert ".mmd" not in mkdocs
    assert ".puml" not in mkdocs
    assert "diagrams.md" in mkdocs
    assert (docs_path / "diagrams.md").exists()


def test_index_has_no_bare_directory_links(temp_package, tmp_path: Path):
    """Les liens vers des répertoires (modules/, api/) font des 404 dans MkDocs."""
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"

    docs_path = SiteBuilder(cfg, pkg).build()

    index = (docs_path / "index.md").read_text()
    assert "](modules/)" not in index
    assert "](api/)" not in index


def test_module_page_has_no_empty_source_section(temp_package, tmp_path: Path):
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"

    docs_path = SiteBuilder(cfg, pkg).build()

    page = (docs_path / "modules" / "testpkg_models.md").read_text()
    assert "## Code source" not in page


def test_enable_search_false_removes_search_plugin(temp_package, tmp_path: Path):
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"
    cfg.enable_search = False

    docs_path = SiteBuilder(cfg, pkg).build()

    mkdocs = (docs_path.parent / "mkdocs.yml").read_text()
    assert "- search" not in mkdocs


def test_focus_svg_only_written_when_svg_format(temp_package, tmp_path: Path):
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"
    cfg.formats = ["mmd"]
    cfg.focus_class = "User"

    docs_path = SiteBuilder(cfg, pkg).build()

    assert (docs_path / "diagrams" / "focus_User.mmd").exists()
    assert not (docs_path / "diagrams" / "focus_User.svg").exists()


def test_builder_public_only(temp_package, tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    pkg = analyze_package(temp_package, package_name="testpkg")

    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.output_dir = tmp_path / "site"
    cfg.docs_dir = tmp_path / "docs"
    cfg.public_only = True

    builder = SiteBuilder(cfg, pkg)
    docs_path = builder.build()

    assert (docs_path / "index.md").exists()


def test_removed_module_leaves_no_orphans(temp_package, tmp_path: Path, monkeypatch):
    """Un module supprimé de la source ne laisse ni page ni diagramme au run suivant."""
    monkeypatch.chdir(tmp_path)
    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.docs_dir = tmp_path / "docs"
    cfg.output_dir = tmp_path / "site"

    pkg = analyze_package(temp_package, package_name="testpkg")
    docs = SiteBuilder(cfg, pkg).build()
    assert (docs / "modules" / "testpkg_services.md").exists()
    assert (docs / "diagrams" / "testpkg_services.mmd").exists()

    (temp_package / "services.py").unlink()
    pkg2 = analyze_package(temp_package, package_name="testpkg")
    docs2 = SiteBuilder(cfg, pkg2).build()

    assert not (docs2 / "modules" / "testpkg_services.md").exists()
    assert not (docs2 / "api" / "testpkg_services.md").exists()
    assert not list((docs2 / "diagrams").glob("testpkg_services.*"))
    assert "testpkg_services" not in (docs2 / "diagrams.md").read_text()


def test_rebuild_produces_identical_file_tree(temp_package, tmp_path: Path, monkeypatch):
    """Deux builds successifs produisent exactement le même ensemble de fichiers."""
    monkeypatch.chdir(tmp_path)
    cfg = GendocConfig()
    cfg.package_path = temp_package
    cfg.docs_dir = tmp_path / "docs"
    cfg.output_dir = tmp_path / "site"
    pkg = analyze_package(temp_package, package_name="testpkg")

    docs = SiteBuilder(cfg, pkg).build()
    first = sorted(p.relative_to(docs) for p in docs.rglob("*") if p.is_file())

    docs = SiteBuilder(cfg, pkg).build()
    second = sorted(p.relative_to(docs) for p in docs.rglob("*") if p.is_file())

    assert first == second
